image: python:3.8-alpine

before_script:
  - apk update && apk add --no-cache build-base linux-headers

stages:
  - format
  - test

format-lib:
  stage: format
  script:
    - pip install black
    - black typocase/
  only:
    refs:
      - master
      - develop
      - feature/gitlab-ci

test-lib:
  stage: test
  script:
    - pip install pytest
    - pytest -v
  only:
    refs:
      - master
      - develop
      - feature/gitlab-ci