repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        name: check-format
        stages: [commit]
        args: ["--verbose"]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        name: check-imports
        stages: [commit]
        args: ["--recursive", "--verbose"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.750
    hooks:
    -   id: mypy
        name: check-types
        stages: [commit]
        args: ["--pretty", "--ignore-missing-imports"]
